### ISSUE TITLE
Decide if its day or night by analyzing frame.

### ISSUE THREAD

**Issue by Risingabhi** [alex-coch/TDI-Machine-Learning#3]
while(cap.isOpened()):
  start = timeit.default_timer()
  ret, frame = cap.read()
  score = np.average(norm(frame, axis=2)) / np.sqrt(3)  #cal day/night  <60 night time. lower light

  if score <60: # send for processing to night.py 
 else send code for processing to run_TDI_Final.py

**Comment by alex-coch** [comment]
I have no access to the run_TDI_Final.py

**Comment by alex-coch** [comment]
if score >= 60:
    import run_TDI_Final
else:
    #the rest of the file night.py
